# Generated by Django 5.0.3 on 2024-03-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
                ('file', models.FileField(upload_to='./uploaded_files')),
            ],
        ),
    ]
